twitch:
  client_id: ':)'
  client_secret: ':)'
  username: ':)'
  channel_file: 'streamers.txt'
mongo:
  host: 'localhost'
postgres:
  dbname: 'mydb'
  username: 'username'
  password: 'password'
  host: 'localhost'
  port: '5432'
