twitch:
  client_id: ':)'
  client_secret: ':)'
  username: ':)'
mongo:
  hosts:
  - host: '127.0.0.1'
    port: 27017
  username: null
  password: null
  options: {}
  authdb: null
  dbname: 'twitch_logger'
